/*
 * Stub for class diaspora.appexamples.wordscramblewithfriends.app.ScrambleManager
 * Generated by Diaspora Compiler (sc).
 */
package diaspora.appexamples.wordscramblewithfriends.app.stubs;


public final class ScrambleManager_Stub extends diaspora.appexamples.wordscramblewithfriends.app.ScrambleManager implements diaspora.common.AppObjectStub {

    diaspora.policy.DiasporaPolicy.DiasporaClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public ScrambleManager_Stub () {
        super();
    }


    public void $__initialize(diaspora.policy.DiasporaPolicy.DiasporaClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of getUserManager()
    public diaspora.appexamples.wordscramblewithfriends.app.UserManager getUserManager() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getUserManager();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public diaspora.appexamples.wordscramblewithfriends.app.UserManager diaspora.appexamples.wordscramblewithfriends.app.ScrambleManager.getUserManager()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((diaspora.appexamples.wordscramblewithfriends.app.UserManager) $__result);
    }

    // Implementation of getTableManager()
    public diaspora.appexamples.wordscramblewithfriends.app.TableManager getTableManager() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getTableManager();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public diaspora.appexamples.wordscramblewithfriends.app.TableManager diaspora.appexamples.wordscramblewithfriends.app.ScrambleManager.getTableManager()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((diaspora.appexamples.wordscramblewithfriends.app.TableManager) $__result);
    }
}
