/*
 * Stub for class diaspora.appexamples.wordscramblewithfriends.app.UserManager
 * Generated by Diaspora Compiler (sc).
 */
package diaspora.appexamples.wordscramblewithfriends.app.stubs;


public final class UserManager_Stub extends diaspora.appexamples.wordscramblewithfriends.app.UserManager implements diaspora.common.AppObjectStub {

    diaspora.policy.DiasporaPolicy.DiasporaClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public UserManager_Stub () {
        super();
    }


    public void $__initialize(diaspora.policy.DiasporaPolicy.DiasporaClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of login(String, String)
    public diaspora.appexamples.wordscramblewithfriends.app.User login(java.lang.String $param_String_1, java.lang.String $param_String_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.login( $param_String_1,  $param_String_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public diaspora.appexamples.wordscramblewithfriends.app.User diaspora.appexamples.wordscramblewithfriends.app.UserManager.login(java.lang.String,java.lang.String)";
                $__params.add($param_String_1);
                $__params.add($param_String_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((diaspora.appexamples.wordscramblewithfriends.app.User) $__result);
    }

    // Implementation of getUser(String)
    public diaspora.appexamples.wordscramblewithfriends.app.User getUser(java.lang.String $param_String_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getUser( $param_String_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public diaspora.appexamples.wordscramblewithfriends.app.User diaspora.appexamples.wordscramblewithfriends.app.UserManager.getUser(java.lang.String)";
                $__params.add($param_String_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((diaspora.appexamples.wordscramblewithfriends.app.User) $__result);
    }

    // Implementation of dhtGetData()
    public java.util.Map dhtGetData() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.dhtGetData();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.Map<diaspora.policy.interfaces.dht.DHTKey, ?> diaspora.appexamples.wordscramblewithfriends.app.UserManager.dhtGetData()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.Map) $__result);
    }

    // Implementation of addUser(String, String)
    public diaspora.appexamples.wordscramblewithfriends.app.User addUser(java.lang.String $param_String_1, java.lang.String $param_String_2)
            throws diaspora.app.AppObjectNotCreatedException {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.addUser( $param_String_1,  $param_String_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public diaspora.appexamples.wordscramblewithfriends.app.User diaspora.appexamples.wordscramblewithfriends.app.UserManager.addUser(java.lang.String,java.lang.String) throws diaspora.app.AppObjectNotCreatedException";
                $__params.add($param_String_1);
                $__params.add($param_String_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((diaspora.appexamples.wordscramblewithfriends.app.User) $__result);
    }
}
