/*
 * Stub for class diaspora.appexamples.wordscramblewithfriends.app.User
 * Generated by Diaspora Compiler (sc).
 */
package diaspora.appexamples.wordscramblewithfriends.app.stubs;


public final class User_Stub extends diaspora.appexamples.wordscramblewithfriends.app.User implements diaspora.common.AppObjectStub {

    diaspora.policy.DiasporaPolicy.DiasporaClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public User_Stub (diaspora.appexamples.wordscramblewithfriends.app.UserInfo $param_UserInfo_1) {
        super($param_UserInfo_1);
    }


    public void $__initialize(diaspora.policy.DiasporaPolicy.DiasporaClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of setNotificationService(NotificationService)
    public void setNotificationService(diaspora.appexamples.wordscramblewithfriends.app.NotificationService $param_NotificationService_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.setNotificationService( $param_NotificationService_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void diaspora.appexamples.wordscramblewithfriends.app.User.setNotificationService(diaspora.appexamples.wordscramblewithfriends.app.NotificationService)";
                $__params.add($param_NotificationService_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of isPlayingGame()
    public boolean isPlayingGame() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.isPlayingGame();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boolean diaspora.appexamples.wordscramblewithfriends.app.User.isPlayingGame()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Boolean) $__result).booleanValue();
    }

    // Implementation of getUserInfo()
    public diaspora.appexamples.wordscramblewithfriends.app.UserInfo getUserInfo() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getUserInfo();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public diaspora.appexamples.wordscramblewithfriends.app.UserInfo diaspora.appexamples.wordscramblewithfriends.app.User.getUserInfo()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((diaspora.appexamples.wordscramblewithfriends.app.UserInfo) $__result);
    }

    // Implementation of getNotificationService()
    public diaspora.appexamples.wordscramblewithfriends.app.NotificationService getNotificationService() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getNotificationService();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public diaspora.appexamples.wordscramblewithfriends.app.NotificationService diaspora.appexamples.wordscramblewithfriends.app.User.getNotificationService()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((diaspora.appexamples.wordscramblewithfriends.app.NotificationService) $__result);
    }

    // Implementation of getGame()
    public diaspora.appexamples.wordscramblewithfriends.app.Game getGame() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getGame();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public diaspora.appexamples.wordscramblewithfriends.app.Game diaspora.appexamples.wordscramblewithfriends.app.User.getGame()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((diaspora.appexamples.wordscramblewithfriends.app.Game) $__result);
    }
}
